name: Release project

on:
  workflow_run:
    workflows:
      - 'Build project'
    branches:
      - 'release/release-*'
    types:
      - completed

jobs:
  buildForAllSupportedPlatforms:
    name: Release for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneWindows # Build a Windows standalone.
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true
      - uses: dawidd6/action-download-artifact@v2
        with:
          name: Build-${{ matrix.targetPlatform }}
          path: build/${{ matrix.targetPlatform }}
          workflow: main.yml
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          tag_name: ${{ github.ref }}-T_3
          release_name: Release ${{ github.ref }} - T_3
          body: Release ${{ github.ref }} - T_3
          draft: false
          prerelease: false
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          upload_url: ${{ github.event.repository.releases_url }}/assets?name=StandaloneWindows.zip
          asset_path: build/${{ matrix.targetPlatform }}
          asset_name: StandaloneWindows.zip
          asset_content_type: application/zip
